### ISSUE TITLE
Cannot set time of file with touch command

### ISSUE THREAD

**Issue by TheGrandPackard** [mgeitz/albumfs#1]
$ touch file1.txt
touch: setting times of `file1.txt': Function not implemented
$ ls -l
-rw-r--r-- 1 packard packard 0 Dec 31  1969 file1.txt

**Comment by mgeitz** [comment]
The size of the root image limits the amount of image and file meta data than can be stored.  Choosing to store access, modified, and created time stamps would drastically decrease the total possible file count for a given root image.
