### ISSUE TITLE
Segmentation Fault when formatting new drive with only 2 PNGs

### ISSUE THREAD

**Issue by TheGrandPackard** [mgeitz/albumfs#4]
This is a case where the user is informed that they do not have enough valid PNGs (minimum 2, but that includes a root, right?), and if the user does not have enough, the application does a segmentation fault. see the logs below:

[josh@localhost ~]$ albumfs -format Background.png 
Enter drive name:
stuff
Enter encryption key for stuff.afs:
qwerasdf
Not enough images in /home/josh/ to create stuff.afs. At least 2 valid PNG images required.
Current valid images:
Segmentation fault (core dumped)
[josh@localhost ~]$ ls -l
total 4072
drwxr-xr-x. 4 root root    4096 Dec  3 08:58 albumfs
-rw-rw-r--. 1 josh josh 2620816 Dec  3 08:59 Background.png
-rw-rw-r--. 1 josh josh 1541760 Dec  3 08:59 Borealis_Background_Neon.png
[josh@localhost ~]$

**Comment by mgeitz** [comment]
Fixed
