### ISSUE TITLE
Add dependency wiki data for distros

### ISSUE THREAD

**Issue by TheGrandPackard** [mgeitz/albumfs#7]
Centos:

- yum group install "Development Tools"
- yum install libpng libpng-devel
- yum install fuse fuse-devel
- yum install openssl openssl-devel

**Comment by mgeitz** [comment]
I'll include this in the wiki; though, rather than iterate through the different package names for each distro I'm thinking it may simplify matters to dockerize albumfs #9

**Comment by mgeitz** [comment]
Resolved by #11
